#pragma once

#define POPUP_WIDTH 400
#define POPUP_HEIGHT 100

#define POPUP_SHOW_TIME_MS 2000
#define POPUP_FADE_TIME_MS 500

#define WHITE_BAR_HEIGHT 10
#define SMALL_FONT_HEIGHT 16
#define REGULAR_FONT_HEIGHT 20
#define LARGE_FONT_HEIGHT 24
#define TEXT_MARGIN_TOP 5